// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjgrgyilffwcgxlghnrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqZ3JneWlsZmZ3Y2d4bGdobnJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4MzcyMjgsImV4cCI6MjA3NTQxMzIyOH0.0RXHmuA6geNCAdd5rqtu5oOa17IThu2hGo5q5fAlovc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});