// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utpowbfvhahdhhbforqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0cG93YmZ2aGFoZGhoYmZvcnFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzUzNTksImV4cCI6MjA3MDY1MTM1OX0.SPFVneOQJAmw8oO6DjomXCypNc02upiyk_JWFrc8I_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});